# -*- coding: utf-8 -*-
"""BreastCancerSNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qu7FfvXC9a4kGRCvJMGfxkQP1dPWVpXV

Dependencies
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn.datasets
from sklearn.model_selection import train_test_split

breast_cancer_dataset = sklearn.datasets.load_breast_cancer()

print(breast_cancer_dataset)

# Adapt data to Pandas
dataframe = pd.DataFrame(breast_cancer_dataset.data, columns = breast_cancer_dataset.feature_names)

dataframe.head()

# Add target column
dataframe['label'] = breast_cancer_dataset.target

dataframe.head()

dataframe.shape

dataframe.info()

# Checking for null values
dataframe.isnull().sum()

dataframe.describe()

# Distribution of target variable
dataframe['label'].value_counts()

"""1 --> Benign Tumor

0 --> Malignant Tumor
"""

dataframe.groupby('label').mean()

# Separating data from target variable

X = dataframe.drop(['label'], axis = 1)
Y = dataframe['label']

print(X)
print(Y)

"""Training/Test Data Split"""

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 42)

"""Data Standardization"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_std = scaler.fit_transform(X_train)

X_test_std = scaler.transform(X_test)

print(X_train_std)

print(X.shape, X_train.shape, X_test.shape)

"""**Building Neural Network**"""

import tensorflow as tf
tf.random.set_seed(3)
from tensorflow import keras

# Neural Network Layers
model = keras.Sequential([keras.layers.Flatten(input_shape=(30,)),
                          keras.layers.Dense(20, activation='relu'),
                          keras.layers.Dense(30, activation='sigmoid'),
                          keras.layers.Dense(2, activation='sigmoid')])

# Neural Network Compiling
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Neural Network Training
history = model.fit(X_train_std, Y_train, validation_split=0.1, epochs=10)

"""Accuracy Visualization"""

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])

plt.title('Model Accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')

plt.legend(['Training Data', 'Validation Data'], loc = 'lower right')

plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])

plt.title('Model Loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')

plt.legend(['Training Data', 'Validation Data'], loc = 'upper right')

# Model Accuracy on test data
loss, accuracy = model.evaluate(X_test_std, Y_test)
print(accuracy)

"""Prediction System"""

Y_pred = model.predict(X_test_std)

print(Y_pred.shape)
print(Y_pred[0])

"""For the first entry on testing data, there is a 23% chance for a malignant tumor, and a 70% chance for a benign tumor."""

print(X_test_std)

print(Y_pred)

"""model.predict() drops the probability for the datapoint to belong to any of the classes"""

# Converting the probabilty to class labels

Y_pred_label = [np.argmax(i) for i in Y_pred]
print(Y_pred_label)

input_data = (13.54,14.36,87.46,566.3,0.09779,0.08129,0.06664,0.04781,0.1885,0.05766,0.2699,0.7886,2.058,23.56,0.008462,0.0146,0.02387,0.01315,0.0198,0.0023,15.11,19.26,99.7,711.2,0.144,0.1773,0.239,0.1288,0.2977,0.07259)

# Convert input_data to numpy array

input_numpy = np.asarray(input_data)
input_reshaped = input_numpy.reshape(1, -1)

# Standardize data

input_std = scaler.transform(input_reshaped)

prediction = model.predict(input_std)

if np.argmax(prediction) == 0:
  print("Malignant tumor")
else:
  print("Benign tumor")