# -*- coding: utf-8 -*-
"""FakeNewsPrediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13_uNvuCr0tqciHvMXDDSZpYAS3PSAn3r

Dataset Structure:

1. id: unique id for a news article
2. title: title of a news article
3. author: author of a news article
4. text: text of the article
5. label: marks whether an article is real or fake
"""

import numpy as np
import pandas as pd
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

import nltk
nltk.download('stopwords')

print(stopwords.words('english'))
# Words that don't add value when analyzing text.

"""Data pre-processing"""

# Load into pandas
news_dataset = pd.read_csv('/content/train.csv')
news_dataset.head()

news_dataset.shape

# Check for missing values
news_dataset.isnull().sum()

# Replace null values with empty string as dataset is large enough to still train model

news_dataset = news_dataset.fillna('')

# Separate data and labels
X = news_dataset.drop(['label'], axis=1)
Y = news_dataset['label']

print(X)
print(Y)

"""*Stemming*: The process of reducing a word to it's root word"""

port_stem = PorterStemmer()

def stemming(text):
  stemmed_text = re.sub('[^a-zA-Z]',' ', text)
  stemmed_text = stemmed_text.lower()
  stemmed_text = stemmed_text.split()
  stemmed_text = [port_stem.stem(word) for word in stemmed_text if not word in stopwords.words('english')]
  stemmed_text = ' '.join(stemmed_text)
  return stemmed_text

news_dataset['text'] = news_dataset['text'].apply(stemming)

print(news_dataset['text'])

"""Convert Text to Vectors"""

X = news_dataset['text'].values
Y = news_dataset['label'].values

print(X)
print(Y)

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(X)

print(X)

"""Training/Test Splitting"""

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, stratify = Y, random_state = 2)

"""Model Training"""

model = LogisticRegression()

model.fit(X_train, Y_train)

"""Model Evaluation"""

# Accuracy on training data

train_prediction = model.predict(X_train)
train_pred_acc = accuracy_score(train_prediction, Y_train)

print(train_pred_acc)

# Accuracy on test data

test_prediction = model.predict(X_test)
test_pred_acc = accuracy_score(test_prediction, Y_test)

print(test_pred_acc)

"""Prediction System"""

input_article_text = X_test[1]

prediction = model.predict(input_article_text)
print(input_article_text)
print(prediction)

if prediction[0] == 0:
  print("Genuine Article")
else:
  print("Fake news")