# -*- coding: utf-8 -*-
"""HousePricePrediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-i7vTtT5v2XCVJVuZG4x45zddkqhef1q

Dependencies
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn.datasets
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor
from sklearn import metrics
from sklearn.datasets import fetch_california_housing

"""Importing California Housing Dataset

"""

housing = fetch_california_housing()
print(housing)

# Loading dataset to Pandas
house_price_dataframe = pd.DataFrame(housing.data, columns=housing.feature_names)
house_price_dataframe.head()

# Incorporate target column to dataframe
house_price_dataframe[housing.target_names[0]] = housing.target
house_price_dataframe.head()

# Dataset Size
house_price_dataframe.shape

# Check for missing values
house_price_dataframe.isnull().sum()

# Dataframe statistics
house_price_dataframe.describe()

"""Correlation between data"""

correlation = house_price_dataframe.corr()

# Correlation Heat Map
plt.figure(figsize=(10,10))
sns.heatmap(correlation, cbar=True, square=True, fmt='.2f', annot=True, annot_kws={'size':8}, cmap='Oranges')

# Split Data and Labels
X = house_price_dataframe.drop(['MedHouseVal'], axis=1)
Y = house_price_dataframe['MedHouseVal']

print(X)
print(Y)

"""Traning/Test Data Split"""

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 2)

print(X.shape, X_train.shape, X_test.shape)

"""Model Training

XGBoost Regressor
"""

model = XGBRegressor()
model.fit(X_train, Y_train)

"""Model Evaluation"""

# Accuracy on training data
training_prediction = model.predict(X_train)

print(training_prediction)

# R Squared Error and Mean Absolute error for regression model accuracy
rsq_error1 = metrics.r2_score(Y_train, training_prediction)

mabs_error1 = metrics.mean_absolute_error(Y_train, training_prediction)

print(rsq_error1)
print(mabs_error1)

"""Visualize real prices and predicted prices"""

plt.scatter(Y_train, training_prediction, alpha=0.5)
plt.xlabel('Actual Prices')
plt.ylabel('Predicted Prices')
plt.title('Actual vs Predicted House Prices')
plt.grid(True)
plt.show()

residuals = Y_train - training_prediction
plt.figure(figsize=(8, 6))
plt.hist(residuals, bins=50, edgecolor='black')
plt.title('Distribution of Residuals')
plt.xlabel('Prediction Error')
plt.ylabel('Frequency')
plt.grid(True)
plt.show()

# Accuracy on test data
testing_prediction = model.predict(X_test)

rsq_error2 = metrics.r2_score(Y_test, testing_prediction)

mabs_error2 = metrics.mean_absolute_error(Y_test, testing_prediction)

print(rsq_error2)
print(mabs_error2)

plt.scatter(Y_test, testing_prediction, alpha=0.5)
plt.xlabel('Actual Prices')
plt.ylabel('Predicted Prices')
plt.title('Actual vs Predicted House Prices')
plt.grid(True)
plt.show()

residuals = Y_train - training_prediction
plt.figure(figsize=(8, 6))
plt.hist(residuals, bins=50, edgecolor='black')
plt.title('Distribution of Residuals')
plt.xlabel('Prediction Error')
plt.ylabel('Frequency')
plt.grid(True)
plt.show()