# -*- coding: utf-8 -*-
"""SonarPrediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kk7s_xxn2GVGsd_9a77-NUPm4xzSj_-3

Dependencies
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

"""Data Collection and Processing"""

sonar_data = pd.read_csv('/content/sample_data/SonarData.csv', header=None)

sonar_data.head()

sonar_data.shape

sonar_data.describe()

sonar_data[60].value_counts()

"""M = Mine
R = Rock
"""

sonar_data.groupby(60).mean()

# Separating data from labels
Data = sonar_data.drop(columns=60, axis=1)
Labels = sonar_data[60]

print(Data)
print(Labels)

"""Training/Test Data"""

X_train, X_test, Y_train, Y_test = train_test_split(Data,
                                                    Labels,
                                                    test_size = 0.1,
                                                    stratify = Labels,
                                                    random_state = 1)

print(Data.shape, X_train.shape, X_test.shape)

"""Model Training (Logistic Regression)"""

model = LogisticRegression()
model.fit(X_train, Y_train)

"""Model Evaluation"""

# Accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

print(X_train_prediction)
print(training_data_accuracy)

# Accuracy on test data
X_test_prediction = model.predict(X_test)
testing_data_accuracy = accuracy_score(X_test_prediction, Y_test)

print(X_test_prediction)
print(testing_data_accuracy)

"""Predictive System"""

input_data = (0.0307,0.0523,0.0653,0.0521,0.0611,0.0577,0.0665,0.0664,0.1460,0.2792,0.3877,0.4992,0.4981,0.4972,0.5607,0.7339,0.8230,0.9173,0.9975,0.9911,0.8240,0.6498,0.5980,0.4862,0.3150,0.1543,0.0989,0.0284,0.1008,0.2636,0.2694,0.2930,0.2925,0.3998,0.3660,0.3172,0.4609,0.4374,0.1820,0.3376,0.6202,0.4448,0.1863,0.1420,0.0589,0.0576,0.0672,0.0269,0.0245,0.0190,0.0063,0.0321,0.0189,0.0137,0.0277,0.0152,0.0052,0.0121,0.0124,0.0055)

# Converting to numpy array
input_data_numpy = np.asarray(input_data)

# Reshape array to avoid model confusion
input_data_reshaped = input_data_numpy.reshape(1, -1)

input_data_reshaped.shape

prediction = model.predict(input_data_reshaped)
print(prediction)

if prediction[0] == 'R':
  print('Rock Detected')
elif prediction[0] == 'M':
  print('Mine Detected')
else:
  print('Unidentified object Detected')