# -*- coding: utf-8 -*-
"""MaskDetectionCNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d_YuurbBM3jrv_4tkxXjRfaZGHzr_0eS

**KAGGLE API REQUIRED**
"""

!pip install kaggle

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

#!/bin/bash
!kaggle datasets download omkargurav/face-mask-dataset

from zipfile import ZipFile
dataset ='/content/face-mask-dataset.zip'

with ZipFile(dataset, 'r') as zip:
  zip.extractall()
  print('Dataset Extracted')

"""Python Dependencies"""

import os
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import cv2
from google.colab.patches import cv2_imshow
from PIL import Image
from sklearn.model_selection import train_test_split

masked_imgs = os.listdir('/content/data/with_mask')
unmasked_imgs = os.listdir('/content/data/without_mask')
print(masked_imgs[0:5])
print(masked_imgs[-5:])
print(unmasked_imgs[0:5])
print(unmasked_imgs[-5:])

print('Ammount of images with masks:', len(masked_imgs))
print('Ammount of images without masks:', len(unmasked_imgs))

# Label creation for each image class
# Unmasked --> 0
# Masked --> 1

masked_lbl = [1]*3725
unmasked_lbl = [0]*3828

"""**Display Images**"""

# Masked
img = mpimg.imread('/content/data/with_mask/with_mask_1060.jpg')
imgplot = plt.imshow(img)
plt.show()

# Unmasked
img = mpimg.imread('/content/data/without_mask/without_mask_1158.jpg')
imgplot = plt.imshow(img)
plt.show()

"""**Image processing**

1. Resize images (constant image size)
2. Convertion to numpy arrays
"""

# Convertion to Numpy
masked_path = '/content/data/with_mask/'
unmasked_path = '/content/data/without_mask/'

data = []

for img_file in masked_imgs:
  image = Image.open(masked_path + img_file)
  image = image.resize((128, 128))
  image = image.convert('RGB')
  image = np.array(image)
  data.append(image)

for img_file in unmasked_imgs:
  image = Image.open(unmasked_path + img_file)
  image = image.resize((128, 128))
  image = image.convert('RGB')
  image = np.array(image)
  data.append(image)

len(data)

data[0]

print(data[0].shape)

# Convert Image list and label list to numpy

X = np.array(data)
Y = np.array(masked_lbl+unmasked_lbl)

print(X.shape) # 7553 arrays of 128x128 pixels and 3 layers (RGB)
print(Y.shape)

"""Training/Testing Data Split"""

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

print(X.shape, X_train.shape, X_test.shape)

# Data Scaling for better model performance
X_train_scaled = X_train/255
X_test_scaled = X_test/255

X_train[0]

X_train_scaled[0]

"""**Convolutional Neural Network**"""

import tensorflow as tf
from tensorflow import keras

num_of_classes = 2
model = keras.Sequential ()

model.add(keras.layers.Conv2D(32,
                              kernel_size=(3,3),
                              activation='relu',
                              input_shape=(128, 128, 3)))

model.add(keras.layers.MaxPooling2D(pool_size=(2,2)))

model.add(keras.layers.Conv2D(64,
                              kernel_size=(3,3),
                              activation='relu'))

model.add(keras.layers.MaxPooling2D(pool_size=(2,2)))

model.add(keras.layers.Flatten())

model.add(keras.layers.Dense(128, activation='relu'))

model.add(keras.layers.Dropout(0.5))

model.add(keras.layers.Dense(64, activation='relu'))

model.add(keras.layers.Dropout(0.5))

model.add(keras.layers.Dense(2, activation='sigmoid'))

# Compile Neural Network
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Training CNN
history = model.fit(X_train_scaled, Y_train, validation_split=0.1, epochs=8)

"""Model Evaluation"""

loss, accuracy = model.evaluate(X_test_scaled, Y_test)
print('Test Accuracy =', accuracy)

# Plot Accuracy
plt.plot(history.history['accuracy'], label = 'Training Accuracy')
plt.plot(history.history['val_accuracy'], label = 'Validation Accuracy')
plt.legend()
plt.show()

# Plot Loss
plt.plot(history.history['loss'], label = 'Training Loss')
plt.plot(history.history['val_loss'], label = 'Validation Loss')
plt.legend()
plt.show()

"""**Prediction System**"""

input_img_path = input('Path of the image to be predicted: ')
input_img = cv2.imread(input_img_path)

cv2_imshow(input_img)

input_img_resize = cv2.resize(input_img, (128,128))

input_img_scaled = input_img_resize/255

input_img_reshape = np.reshape(input_img_scaled, [1, 128, 128, 3])

input_prediction = model.predict(input_img_reshape)

print(input_prediction)

input_pred_label = np.argmax(input_prediction)

print(input_pred_label)

if input_pred_label == 1:
  print('There is a person wearing a mask')
else:
  print('The person in the image is not wearing a mask')