# -*- coding: utf-8 -*-
"""DiabetesPrediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1truMDCzQG79A0J_U2kNXvf2gm1gahrAe

Dependencies
"""

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

"""Data Collection and Analysis

PIMA Diabetes Dataset

"""

diabetes_dataset = pd.read_csv('/content/sample_data/MedicalInformation.csv')
diabetes_dataset.head()

# Dataset Size
diabetes_dataset.shape

# Dataset Statistics

diabetes_dataset.describe()

diabetes_dataset['Outcome'].value_counts()

"""0 = Non-diabetic patient

1 = Diabetic patient
"""

diabetes_dataset.groupby('Outcome').mean()

# Data and Label separation
X = diabetes_dataset.drop(columns = 'Outcome', axis=1)
Y = diabetes_dataset['Outcome']

print(X)
print(Y)

"""Data Standardization"""

scaler = StandardScaler()

scaler.fit(X)

X_standardized = scaler.transform(X) #scaler.fit_transform(X)

print(X_standardized)

"""Traning/Test Data Split"""

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, stratify=Y, random_state=2)

print(X.shape, X_train.shape, X_test.shape)

"""Model Training"""

classifier = svm.SVC(kernel='linear')

# Training Support Vector Machine
classifier.fit(X_train, Y_train)

"""Model Evaluation"""

# Accuracy Score on traning data.
X_train_prediction = classifier.predict(X_train)
training_accuracy = accuracy_score(X_train_prediction, Y_train)
print('Accuracy score of training data =', training_accuracy)

X_train_prediction

# Accuracy Score on test data
X_test_prediction = classifier.predict(X_test)
testing_accuracy = accuracy_score(X_test_prediction, Y_test)
print('Accuracy score of testing data =', testing_accuracy)

X_test_prediction

"""Predictive System"""

input_data = (9,171,110,24,240,45.4,0.721,54)

# Convert input to numpy array and reshape for model

input_data_numpy = np.asarray(input_data)
input_data_reshaped = input_data_numpy.reshape(1, -1)

#Standardize input
std_input = scaler.transform(input_data_reshaped)
print(std_input)
prediction = classifier.predict(std_input)
print(prediction)
if prediction[0] == 0:
  print('Patient is not diabetic')
else:
  print('Patient is diabetic')